/* tslint:disable */
/* eslint-disable */

/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@194.87.226.194:5432/magnit -t absence_reasons_dictionary -t account -t annual_leave -t contact_person -t department_employee -t employee_absence -t employee_rates -t employee_schedule -t employee_weekly_report -t employees -t foreign_passport -t inventory -t military_id -t noncompliance_report -t passport -t positions -t suppliers -t system_access_log -t system_role -s personnel_accounting
 *
 */

export type Json = unknown;
export type week_days =
  | 'Monday'
  | 'Tuesday'
  | 'Wednesday'
  | 'Thursday'
  | 'Friday'
  | 'Saturday'
  | 'Sunday';

// Table absence_reasons_dictionary
export interface AbsenceReasonsDictionary {
  reason_id: number;
  reason_name: string | null;
  reason_description: string | null;
}
export interface AbsenceReasonsDictionaryInput {
  reason_id?: number;
  reason_name?: string | null;
  reason_description?: string | null;
}
const absence_reasons_dictionary = {
  tableName: 'absence_reasons_dictionary',
  columns: ['reason_id', 'reason_name', 'reason_description'],
  requiredForInsert: [],
  primaryKey: 'reason_id',
  foreignKeys: {},
  $type: null as unknown as AbsenceReasonsDictionary,
  $input: null as unknown as AbsenceReasonsDictionaryInput,
} as const;

// Table account
export interface Account {
  employee_id: number | null;
  system_login: string | null;
  system_password: string | null;
}
export interface AccountInput {
  employee_id?: number | null;
  system_login?: string | null;
  system_password?: string | null;
}
const account = {
  tableName: 'account',
  columns: ['employee_id', 'system_login', 'system_password'],
  requiredForInsert: [],
  primaryKey: null,
  foreignKeys: {
    employee_id: {
      table: 'employees',
      column: 'employee_id',
      $type: null as unknown as Employees,
    },
  },
  $type: null as unknown as Account,
  $input: null as unknown as AccountInput,
} as const;

// Table annual_leave
export interface AnnualLeave {
  leave_record_id: number;
  employee_id: number | null;
  year: number | null;
  remaining_leave_days: number | null;
}
export interface AnnualLeaveInput {
  leave_record_id?: number;
  employee_id?: number | null;
  year?: number | null;
  remaining_leave_days?: number | null;
}
const annual_leave = {
  tableName: 'annual_leave',
  columns: ['leave_record_id', 'employee_id', 'year', 'remaining_leave_days'],
  requiredForInsert: [],
  primaryKey: 'leave_record_id',
  foreignKeys: {},
  $type: null as unknown as AnnualLeave,
  $input: null as unknown as AnnualLeaveInput,
} as const;

// Table contact_person
export interface ContactPerson {
  contact_person_id: number;
  last_name: string | null;
  first_name: string | null;
  middle_name: string | null;
  work_phone: number | null;
  personal_phone: number | null;
  social_network_link: Json | null;
}
export interface ContactPersonInput {
  contact_person_id?: number;
  last_name?: string | null;
  first_name?: string | null;
  middle_name?: string | null;
  work_phone?: number | null;
  personal_phone?: number | null;
  social_network_link?: Json | null;
}
const contact_person = {
  tableName: 'contact_person',
  columns: [
    'contact_person_id',
    'last_name',
    'first_name',
    'middle_name',
    'work_phone',
    'personal_phone',
    'social_network_link',
  ],
  requiredForInsert: [],
  primaryKey: 'contact_person_id',
  foreignKeys: {},
  $type: null as unknown as ContactPerson,
  $input: null as unknown as ContactPersonInput,
} as const;

// Table department_employee
export interface DepartmentEmployee {
  employee_id: number;
  department_id: number;
}
export interface DepartmentEmployeeInput {
  employee_id: number;
  department_id: number;
}
const department_employee = {
  tableName: 'department_employee',
  columns: ['employee_id', 'department_id'],
  requiredForInsert: ['employee_id', 'department_id'],
  primaryKey: 'employee_id',
  foreignKeys: {
    employee_id: {
      table: 'employees',
      column: 'employee_id',
      $type: null as unknown as Employees,
    },
  },
  $type: null as unknown as DepartmentEmployee,
  $input: null as unknown as DepartmentEmployeeInput,
} as const;

// Table employee_absence
export interface EmployeeAbsence {
  absence_record_id: number;
  employee_id: number | null;
  start_date: Date | null;
  absence_duration: number | null;
  reason_id: number | null;
  comment: string | null;
  additional_document_available: boolean | null;
}
export interface EmployeeAbsenceInput {
  absence_record_id?: number;
  employee_id?: number | null;
  start_date?: Date | null;
  absence_duration?: number | null;
  reason_id?: number | null;
  comment?: string | null;
  additional_document_available?: boolean | null;
}
const employee_absence = {
  tableName: 'employee_absence',
  columns: [
    'absence_record_id',
    'employee_id',
    'start_date',
    'absence_duration',
    'reason_id',
    'comment',
    'additional_document_available',
  ],
  requiredForInsert: [],
  primaryKey: 'absence_record_id',
  foreignKeys: {
    reason_id: {
      table: 'absence_reasons_dictionary',
      column: 'reason_id',
      $type: null as unknown as AbsenceReasonsDictionary,
    },
  },
  $type: null as unknown as EmployeeAbsence,
  $input: null as unknown as EmployeeAbsenceInput,
} as const;

// Table employee_rates
export interface EmployeeRates {
  position_id: number | null;
  employee_id: number | null;
  weekly_hours: number | null;
}
export interface EmployeeRatesInput {
  position_id?: number | null;
  employee_id?: number | null;
  weekly_hours?: number | null;
}
const employee_rates = {
  tableName: 'employee_rates',
  columns: ['position_id', 'employee_id', 'weekly_hours'],
  requiredForInsert: [],
  primaryKey: null,
  foreignKeys: {
    position_id: {
      table: 'positions',
      column: 'position_id',
      $type: null as unknown as Positions,
    },
    employee_id: {
      table: 'employees',
      column: 'employee_id',
      $type: null as unknown as Employees,
    },
  },
  $type: null as unknown as EmployeeRates,
  $input: null as unknown as EmployeeRatesInput,
} as const;

// Table employee_schedule
export interface EmployeeSchedule {
  schedule_id: number;
  employee_id: number | null;
  attendance_days: week_days[] | null;
  shift_start_time: string | null;
  shift_end_time: string | null;
}
export interface EmployeeScheduleInput {
  schedule_id?: number;
  employee_id?: number | null;
  attendance_days?: week_days[] | null;
  shift_start_time?: string | null;
  shift_end_time?: string | null;
}
const employee_schedule = {
  tableName: 'employee_schedule',
  columns: [
    'schedule_id',
    'employee_id',
    'attendance_days',
    'shift_start_time',
    'shift_end_time',
  ],
  requiredForInsert: [],
  primaryKey: 'schedule_id',
  foreignKeys: {
    employee_id: {
      table: 'employees',
      column: 'employee_id',
      $type: null as unknown as Employees,
    },
  },
  $type: null as unknown as EmployeeSchedule,
  $input: null as unknown as EmployeeScheduleInput,
} as const;

// Table employee_weekly_report
export interface EmployeeWeeklyReport {
  report_id: number;
  employee_id: number | null;
  week_number: number | null;
  overtime_hours: number | null;
  shortfall_hours: number | null;
  confirmation: boolean | null;
}
export interface EmployeeWeeklyReportInput {
  report_id?: number;
  employee_id?: number | null;
  week_number?: number | null;
  overtime_hours?: number | null;
  shortfall_hours?: number | null;
  confirmation?: boolean | null;
}
const employee_weekly_report = {
  tableName: 'employee_weekly_report',
  columns: [
    'report_id',
    'employee_id',
    'week_number',
    'overtime_hours',
    'shortfall_hours',
    'confirmation',
  ],
  requiredForInsert: [],
  primaryKey: 'report_id',
  foreignKeys: {},
  $type: null as unknown as EmployeeWeeklyReport,
  $input: null as unknown as EmployeeWeeklyReportInput,
} as const;

// Table employees
export interface Employees {
  employee_id: number;
  last_name: string | null;
  first_name: string | null;
  middle_name: string | null;
  birth_date: Date | null;
  department_id: number | null;
  role_id: number | null;
  work_phone: number | null;
  personal_phone: number | null;
  email: string | null;
  inn: number | null;
  snils: number | null;
  hire_date: Date | null;
  medical_check_date: Date | null;
  gender: boolean | null;
}
export interface EmployeesInput {
  employee_id?: number;
  last_name?: string | null;
  first_name?: string | null;
  middle_name?: string | null;
  birth_date?: Date | null;
  department_id?: number | null;
  role_id?: number | null;
  work_phone?: number | null;
  personal_phone?: number | null;
  email?: string | null;
  inn?: number | null;
  snils?: number | null;
  hire_date?: Date | null;
  medical_check_date?: Date | null;
  gender?: boolean | null;
}
const employees = {
  tableName: 'employees',
  columns: [
    'employee_id',
    'last_name',
    'first_name',
    'middle_name',
    'birth_date',
    'department_id',
    'role_id',
    'work_phone',
    'personal_phone',
    'email',
    'inn',
    'snils',
    'hire_date',
    'medical_check_date',
    'gender',
  ],
  requiredForInsert: [],
  primaryKey: 'employee_id',
  foreignKeys: {
    role_id: {
      table: 'system_role',
      column: 'role_id',
      $type: null as unknown as SystemRole,
    },
  },
  $type: null as unknown as Employees,
  $input: null as unknown as EmployeesInput,
} as const;

// Table foreign_passport
export interface ForeignPassport {
  passport_id: number;
  employee_id: number | null;
  last_name: string | null;
  first_name: string | null;
  middle_name: string | null;
  gender: boolean | null;
  number: number | null;
  citizenship: string | null;
  department_code: number | null;
  birth_date: Date | null;
  issue_date: Date | null;
  expiry_date: Date | null;
}
export interface ForeignPassportInput {
  passport_id?: number;
  employee_id?: number | null;
  last_name?: string | null;
  first_name?: string | null;
  middle_name?: string | null;
  gender?: boolean | null;
  number?: number | null;
  citizenship?: string | null;
  department_code?: number | null;
  birth_date?: Date | null;
  issue_date?: Date | null;
  expiry_date?: Date | null;
}
const foreign_passport = {
  tableName: 'foreign_passport',
  columns: [
    'passport_id',
    'employee_id',
    'last_name',
    'first_name',
    'middle_name',
    'gender',
    'number',
    'citizenship',
    'department_code',
    'birth_date',
    'issue_date',
    'expiry_date',
  ],
  requiredForInsert: [],
  primaryKey: 'passport_id',
  foreignKeys: {
    employee_id: {
      table: 'employees',
      column: 'employee_id',
      $type: null as unknown as Employees,
    },
  },
  $type: null as unknown as ForeignPassport,
  $input: null as unknown as ForeignPassportInput,
} as const;

// Table inventory
export interface Inventory {
  inventory_id: number;
  date_performed: Date | null;
  inspector_id: number | null;
  store_id: number | null;
  inventory_success: boolean | null;
}
export interface InventoryInput {
  inventory_id?: number;
  date_performed?: Date | null;
  inspector_id?: number | null;
  store_id?: number | null;
  inventory_success?: boolean | null;
}
const inventory = {
  tableName: 'inventory',
  columns: [
    'inventory_id',
    'date_performed',
    'inspector_id',
    'store_id',
    'inventory_success',
  ],
  requiredForInsert: [],
  primaryKey: 'inventory_id',
  foreignKeys: {},
  $type: null as unknown as Inventory,
  $input: null as unknown as InventoryInput,
} as const;

// Table military_id
export interface MilitaryId {
  military_id_number: number;
  employee_id: number | null;
  last_name: string | null;
  first_name: string | null;
  middle_name: string | null;
  commissariat_address: string | null;
  place_of_birth: string | null;
  education: string | null;
  category: string | null;
}
export interface MilitaryIdInput {
  military_id_number: number;
  employee_id?: number | null;
  last_name?: string | null;
  first_name?: string | null;
  middle_name?: string | null;
  commissariat_address?: string | null;
  place_of_birth?: string | null;
  education?: string | null;
  category?: string | null;
}
const military_id = {
  tableName: 'military_id',
  columns: [
    'military_id_number',
    'employee_id',
    'last_name',
    'first_name',
    'middle_name',
    'commissariat_address',
    'place_of_birth',
    'education',
    'category',
  ],
  requiredForInsert: ['military_id_number'],
  primaryKey: 'military_id_number',
  foreignKeys: {
    employee_id: {
      table: 'employees',
      column: 'employee_id',
      $type: null as unknown as Employees,
    },
  },
  $type: null as unknown as MilitaryId,
  $input: null as unknown as MilitaryIdInput,
} as const;

// Table noncompliance_report
export interface NoncomplianceReport {
  report_id: number;
  inventory_id: number | null;
  report_date: Date | null;
  product_barcode: number | null;
  problem_description: string | null;
}
export interface NoncomplianceReportInput {
  report_id?: number;
  inventory_id?: number | null;
  report_date?: Date | null;
  product_barcode?: number | null;
  problem_description?: string | null;
}
const noncompliance_report = {
  tableName: 'noncompliance_report',
  columns: [
    'report_id',
    'inventory_id',
    'report_date',
    'product_barcode',
    'problem_description',
  ],
  requiredForInsert: [],
  primaryKey: 'report_id',
  foreignKeys: {
    inventory_id: {
      table: 'inventory',
      column: 'inventory_id',
      $type: null as unknown as Inventory,
    },
  },
  $type: null as unknown as NoncomplianceReport,
  $input: null as unknown as NoncomplianceReportInput,
} as const;

// Table passport
export interface Passport {
  passport_id: number;
  employee_id: number | null;
  last_name: string | null;
  first_name: string | null;
  middle_name: string | null;
  gender: boolean | null;
  series: number | null;
  number: number | null;
  department_code: number | null;
  registration_address: string | null;
  birth_date: Date | null;
  issue_date: Date | null;
}
export interface PassportInput {
  passport_id?: number;
  employee_id?: number | null;
  last_name?: string | null;
  first_name?: string | null;
  middle_name?: string | null;
  gender?: boolean | null;
  series?: number | null;
  number?: number | null;
  department_code?: number | null;
  registration_address?: string | null;
  birth_date?: Date | null;
  issue_date?: Date | null;
}
const passport = {
  tableName: 'passport',
  columns: [
    'passport_id',
    'employee_id',
    'last_name',
    'first_name',
    'middle_name',
    'gender',
    'series',
    'number',
    'department_code',
    'registration_address',
    'birth_date',
    'issue_date',
  ],
  requiredForInsert: [],
  primaryKey: 'passport_id',
  foreignKeys: {
    employee_id: {
      table: 'employees',
      column: 'employee_id',
      $type: null as unknown as Employees,
    },
  },
  $type: null as unknown as Passport,
  $input: null as unknown as PassportInput,
} as const;

// Table positions
export interface Positions {
  position_id: number;
  position_name: string | null;
  salary: number | null;
  position_description: string | null;
}
export interface PositionsInput {
  position_id?: number;
  position_name?: string | null;
  salary?: number | null;
  position_description?: string | null;
}
const positions = {
  tableName: 'positions',
  columns: ['position_id', 'position_name', 'salary', 'position_description'],
  requiredForInsert: [],
  primaryKey: 'position_id',
  foreignKeys: {},
  $type: null as unknown as Positions,
  $input: null as unknown as PositionsInput,
} as const;

// Table suppliers
export interface Suppliers {
  supplier_id: number;
  supplier_name: string | null;
  taxpayer_id: string | null;
  registration_id: string | null;
  legal_address: string | null;
  actual_address: string | null;
  mobile_phone: string | null;
  email: string | null;
  manager_phone: string | null;
}
export interface SuppliersInput {
  supplier_id?: number;
  supplier_name?: string | null;
  taxpayer_id?: string | null;
  registration_id?: string | null;
  legal_address?: string | null;
  actual_address?: string | null;
  mobile_phone?: string | null;
  email?: string | null;
  manager_phone?: string | null;
}
const suppliers = {
  tableName: 'suppliers',
  columns: [
    'supplier_id',
    'supplier_name',
    'taxpayer_id',
    'registration_id',
    'legal_address',
    'actual_address',
    'mobile_phone',
    'email',
    'manager_phone',
  ],
  requiredForInsert: [],
  primaryKey: 'supplier_id',
  foreignKeys: {},
  $type: null as unknown as Suppliers,
  $input: null as unknown as SuppliersInput,
} as const;

// Table system_access_log
export interface SystemAccessLog {
  log_id: number;
  employee_id: number | null;
  position_id: number | null;
  login_time: string | null;
  logout_time: string | null;
  log_date: Date | null;
}
export interface SystemAccessLogInput {
  log_id?: number;
  employee_id?: number | null;
  position_id?: number | null;
  login_time?: string | null;
  logout_time?: string | null;
  log_date?: Date | null;
}
const system_access_log = {
  tableName: 'system_access_log',
  columns: [
    'log_id',
    'employee_id',
    'position_id',
    'login_time',
    'logout_time',
    'log_date',
  ],
  requiredForInsert: [],
  primaryKey: 'log_id',
  foreignKeys: {},
  $type: null as unknown as SystemAccessLog,
  $input: null as unknown as SystemAccessLogInput,
} as const;

// Table system_role
export interface SystemRole {
  role_id: number;
  role_name: string | null;
}
export interface SystemRoleInput {
  role_id?: number;
  role_name?: string | null;
}
const system_role = {
  tableName: 'system_role',
  columns: ['role_id', 'role_name'],
  requiredForInsert: [],
  primaryKey: 'role_id',
  foreignKeys: {},
  $type: null as unknown as SystemRole,
  $input: null as unknown as SystemRoleInput,
} as const;

export interface TableTypes {
  absence_reasons_dictionary: {
    select: AbsenceReasonsDictionary;
    input: AbsenceReasonsDictionaryInput;
  };
  account: {
    select: Account;
    input: AccountInput;
  };
  annual_leave: {
    select: AnnualLeave;
    input: AnnualLeaveInput;
  };
  contact_person: {
    select: ContactPerson;
    input: ContactPersonInput;
  };
  department_employee: {
    select: DepartmentEmployee;
    input: DepartmentEmployeeInput;
  };
  employee_absence: {
    select: EmployeeAbsence;
    input: EmployeeAbsenceInput;
  };
  employee_rates: {
    select: EmployeeRates;
    input: EmployeeRatesInput;
  };
  employee_schedule: {
    select: EmployeeSchedule;
    input: EmployeeScheduleInput;
  };
  employee_weekly_report: {
    select: EmployeeWeeklyReport;
    input: EmployeeWeeklyReportInput;
  };
  employees: {
    select: Employees;
    input: EmployeesInput;
  };
  foreign_passport: {
    select: ForeignPassport;
    input: ForeignPassportInput;
  };
  inventory: {
    select: Inventory;
    input: InventoryInput;
  };
  military_id: {
    select: MilitaryId;
    input: MilitaryIdInput;
  };
  noncompliance_report: {
    select: NoncomplianceReport;
    input: NoncomplianceReportInput;
  };
  passport: {
    select: Passport;
    input: PassportInput;
  };
  positions: {
    select: Positions;
    input: PositionsInput;
  };
  suppliers: {
    select: Suppliers;
    input: SuppliersInput;
  };
  system_access_log: {
    select: SystemAccessLog;
    input: SystemAccessLogInput;
  };
  system_role: {
    select: SystemRole;
    input: SystemRoleInput;
  };
}

export const tables = {
  absence_reasons_dictionary,
  account,
  annual_leave,
  contact_person,
  department_employee,
  employee_absence,
  employee_rates,
  employee_schedule,
  employee_weekly_report,
  employees,
  foreign_passport,
  inventory,
  military_id,
  noncompliance_report,
  passport,
  positions,
  suppliers,
  system_access_log,
  system_role,
};
