/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@magnit-db.ayarayarovich.ru:5432/magnit -t head_company_response -t orders_on_price_list -t price_list -t price_list_in_order -t price_type -t promotion -t request_to_head_company -t response_status -s pricing
 *
 */


export type Json = unknown;

// Table head_company_response
export interface HeadCompanyResponse {
  response_id: number;
  employee_id: number | null;
  response_date: Date | null;
  response_status_id: number | null;
}
export interface HeadCompanyResponseInput {
  response_id?: number;
  employee_id?: number | null;
  response_date?: Date | null;
  response_status_id?: number | null;
}
const head_company_response = {
  tableName: 'head_company_response',
  columns: ['response_id', 'employee_id', 'response_date', 'response_status_id'],
  requiredForInsert: [],
  primaryKey: 'response_id',
  foreignKeys: { response_status_id: { table: 'response_status', column: 'response_status_id', $type: null as unknown as ResponseStatus }, },
  $type: null as unknown as HeadCompanyResponse,
  $input: null as unknown as HeadCompanyResponseInput
} as const;

// Table orders_on_price_list
export interface OrdersOnPriceList {
  order_id: number;
  order_date: Date | null;
  employee_id: number | null;
}
export interface OrdersOnPriceListInput {
  order_id?: number;
  order_date?: Date | null;
  employee_id?: number | null;
}
const orders_on_price_list = {
  tableName: 'orders_on_price_list',
  columns: ['order_id', 'order_date', 'employee_id'],
  requiredForInsert: [],
  primaryKey: 'order_id',
  foreignKeys: {},
  $type: null as unknown as OrdersOnPriceList,
  $input: null as unknown as OrdersOnPriceListInput
} as const;

// Table price_list
export interface PriceList {
  price_list_id: number;
  location_id: number | null;
  order_id: number | null;
  price_type_id: number | null;
  barcode: number | null;
  item_price: number | null;
  creation_date: Date | null;
}
export interface PriceListInput {
  price_list_id?: number;
  location_id?: number | null;
  order_id?: number | null;
  price_type_id?: number | null;
  barcode?: number | null;
  item_price?: number | null;
  creation_date?: Date | null;
}
const price_list = {
  tableName: 'price_list',
  columns: ['price_list_id', 'location_id', 'order_id', 'price_type_id', 'barcode', 'item_price', 'creation_date'],
  requiredForInsert: [],
  primaryKey: 'price_list_id',
  foreignKeys: {
    location_id: { table: 'storage_spaces', column: 'id_storage_space', $type: null as unknown /* storage_spaces */ },
    order_id: { table: 'orders_on_price_list', column: 'order_id', $type: null as unknown as OrdersOnPriceList },
    price_type_id: { table: 'price_type', column: 'price_type_id', $type: null as unknown as PriceType },
  },
  $type: null as unknown as PriceList,
  $input: null as unknown as PriceListInput
} as const;

// Table price_list_in_order
export interface PriceListInOrder {
  id_price: number;
  order_id: number | null;
  price_list_id: number | null;
}
export interface PriceListInOrderInput {
  id_price?: number;
  order_id?: number | null;
  price_list_id?: number | null;
}
const price_list_in_order = {
  tableName: 'price_list_in_order',
  columns: ['id_price', 'order_id', 'price_list_id'],
  requiredForInsert: [],
  primaryKey: 'id_price',
  foreignKeys: {
    order_id: { table: 'orders_on_price_list', column: 'order_id', $type: null as unknown as OrdersOnPriceList },
    price_list_id: { table: 'price_list', column: 'price_list_id', $type: null as unknown as PriceList },
  },
  $type: null as unknown as PriceListInOrder,
  $input: null as unknown as PriceListInOrderInput
} as const;

// Table price_type
export interface PriceType {
  price_type_id: number;
  price_type_name: string | null;
  price_type_description: string | null;
}
export interface PriceTypeInput {
  price_type_id?: number;
  price_type_name?: string | null;
  price_type_description?: string | null;
}
const price_type = {
  tableName: 'price_type',
  columns: ['price_type_id', 'price_type_name', 'price_type_description'],
  requiredForInsert: [],
  primaryKey: 'price_type_id',
  foreignKeys: {},
  $type: null as unknown as PriceType,
  $input: null as unknown as PriceTypeInput
} as const;

// Table promotion
export interface Promotion {
  promotion_id: number;
  item_id: number | null;
  promotion_name: string | null;
  promotion_date: Date | null;
  promotion_description: string | null;
}
export interface PromotionInput {
  promotion_id?: number;
  item_id?: number | null;
  promotion_name?: string | null;
  promotion_date?: Date | null;
  promotion_description?: string | null;
}
const promotion = {
  tableName: 'promotion',
  columns: ['promotion_id', 'item_id', 'promotion_name', 'promotion_date', 'promotion_description'],
  requiredForInsert: [],
  primaryKey: 'promotion_id',
  foreignKeys: { item_id: { table: 'goods', column: 'barcode', $type: null as unknown /* goods */ }, },
  $type: null as unknown as Promotion,
  $input: null as unknown as PromotionInput
} as const;

// Table request_to_head_company
export interface RequestToHeadCompany {
  request_id: number;
  request_creation_date: Date | null;
  manager_id: number | null;
  item_barcode: number | null;
  acceptance_status_id: number | null;
  response_id: number | null;
  quantity: number | null;
}
export interface RequestToHeadCompanyInput {
  request_id?: number;
  request_creation_date?: Date | null;
  manager_id?: number | null;
  item_barcode?: number | null;
  acceptance_status_id?: number | null;
  response_id?: number | null;
  quantity?: number | null;
}
const request_to_head_company = {
  tableName: 'request_to_head_company',
  columns: ['request_id', 'request_creation_date', 'manager_id', 'item_barcode', 'acceptance_status_id', 'response_id', 'quantity'],
  requiredForInsert: [],
  primaryKey: 'request_id',
  foreignKeys: {
    item_barcode: { table: 'goods', column: 'barcode', $type: null as unknown /* goods */ },
    response_id: { table: 'head_company_response', column: 'response_id', $type: null as unknown as HeadCompanyResponse },
  },
  $type: null as unknown as RequestToHeadCompany,
  $input: null as unknown as RequestToHeadCompanyInput
} as const;

// Table response_status
export interface ResponseStatus {
  response_status_id: number;
  response_status_name: string | null;
  response_status_description: string | null;
}
export interface ResponseStatusInput {
  response_status_id?: number;
  response_status_name?: string | null;
  response_status_description?: string | null;
}
const response_status = {
  tableName: 'response_status',
  columns: ['response_status_id', 'response_status_name', 'response_status_description'],
  requiredForInsert: [],
  primaryKey: 'response_status_id',
  foreignKeys: {},
  $type: null as unknown as ResponseStatus,
  $input: null as unknown as ResponseStatusInput
} as const;


export interface TableTypes {
  head_company_response: {
    select: HeadCompanyResponse;
    input: HeadCompanyResponseInput;
  };
  orders_on_price_list: {
    select: OrdersOnPriceList;
    input: OrdersOnPriceListInput;
  };
  price_list: {
    select: PriceList;
    input: PriceListInput;
  };
  price_list_in_order: {
    select: PriceListInOrder;
    input: PriceListInOrderInput;
  };
  price_type: {
    select: PriceType;
    input: PriceTypeInput;
  };
  promotion: {
    select: Promotion;
    input: PromotionInput;
  };
  request_to_head_company: {
    select: RequestToHeadCompany;
    input: RequestToHeadCompanyInput;
  };
  response_status: {
    select: ResponseStatus;
    input: ResponseStatusInput;
  };
}

export const tables = {
  head_company_response,
  orders_on_price_list,
  price_list,
  price_list_in_order,
  price_type,
  promotion,
  request_to_head_company,
  response_status,
}
